[build]
command = "npm ci && npm run build -- --configuration production"
# da das Frontend im Unterordner 'frontend' liegt, musst du hier 'frontend/dist/frontend' angeben
publish = "frontend/dist/frontend"

[[redirects]]
from = "/*"
to   = "/index.html"
status = 200
